### ISSUE TITLE
Timeout when creating a docker volume?

### ISSUE THREAD

**Issue by davirtavares** [LINBIT/linstor-docker-volume#1]
`docker volume create -d linstor --opt fs=ext4 --opt size=800 test`

The command above takes forever to finish, and it throws the following error:

`Error response from daemon: create test: Post http://%2Frun%2Fdocker%2Fplugins%2Flinstor.sock/VolumeDriver.Create: context deadline exceeded`

Running the command a second time the volume gets created:

```
root@kfc4445red0:~$ docker volume list
DRIVER              VOLUME NAME
linstor             test
```

But running a container fails:

```
root@kfc4445red0:/tmp$ docker run --name some-mongo -v test:/data/db -d mongo
Unable to find image 'mongo:latest' locally
latest: Pulling from library/mongo
Digest: sha256:720cbcd65b0212f312f50cb006ab9058af20962f1de7214158ac74343a891c8a
Status: Downloaded newer image for mongo:latest
docker: Error response from daemon: Could not mount /dev/drbd1002 to /run/docker/linstor/mnt/test.
See 'docker run --help'.
```

Trying to mount the same device in another mount point:

```
root@kfc4445red0:/tmp$ mount /dev/drbd1002 /mnt
mount: wrong fs type, bad option, bad superblock on /dev/drbd1002,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

After realizing that the device hasn't been formatted we ran mkfs in it and were able to mount and use it in the container. But I believe that there's some sort of timeout occurring the volume creation.

**Comment by rck** [comment]
I'm pretty sure this isn't a bug in the plugin itself, it is a combination of docker timeout, mkfs, and DRBD.

The problem here is that by default mkfs.ext4 tries to discard the storage. But that can take a long time, depending on what the storage on all peers reports as its capabilities. Longer than Docker is willing to wait. For the plugin you can also set file system options (on the CLI or via the config file). For ext4 one could try `-E nodiscard`.

If that does not help, you could add `print`s in the area where mkfs is called and test the plugin without starting it as systemd service and without docker. Just start it locally `./linstor-docker-volume` and call something like that:
```
$ sudo curl --unix-socket /run/docker/plugins/linstor.sock -X POST -H "Content-Type: application/json" -d '{"Name":"dockervol42"}' http://localhost/VolumeDriver.Create
$ drbdsetup status # to see if it looks good from a DRBD point of view
$ sudo curl --unix-socket /run/docker/plugins/linstor.sock -X POST -H "Content-Type: application/json" -d '{"Name":"dockervol42"}' http://localhost/VolumeDriver.Mount
$ mount # to check if it got mounted
$ sudo curl --unix-socket /run/docker/plugins/linstor.sock -X POST -H "Content-Type: application/json" -d '{"Name":"dockervol42"}' http://localhost/VolumeDriver.Unmount
$ linstor rd d dockervol42 # to remove it
```

This should make it easier to debug things. That said, I'm pretty sure `mkfs` taking too long on DRBD with default options is what is happening here. In any case this needs more documentation. Maybe the plugin could get better and add these options for the most common file systems on its own.

**Comment by rck** [comment]
I pushed an updated `README.md`. As I'm pretty sure that was the case for the problem and as there has not been any feedback, I'm closing that issue.
